import Head from "next/head";
import styled from "styled-components";
import { Card } from "@/components/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tip Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main>
        <Wrapper>
          <Card />
        </Wrapper>
      </main>
    </>
  );
}

const Wrapper = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  margin: auto;
`;
